[package]
name = "sdk-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iota-sdk = { path = "../../iota-sdk/sdk", default-features = false, features = [ "wallet", "stronghold", "rand" ] }
tokio = { version = "1.26" }
dotenvy = { version = "0.15" }
lazy_static = { version = "1.4" }
rand = { version = "0.8", features = ["small_rng"] }
serde = "1.0"
serde_json = "1.0"
packable = "0.7.0"
hex = "0.4.3"
thiserror = { version = "1.0.40" }
iota-crypto = { version = "0.23.0", default-features = false, features = [
    "blake2b"
] }